from django.db import models


class DepartamentoColombia(models.TextChoices):
    AMAZONAS = 'Amazonas', 'Amazonas'
    ANTIOQUIA = 'Antioquia', 'Antioquia'
    ARAUCA = 'Arauca', 'Arauca'
    ATLANTICO = 'Atlántico', 'Atlántico'
    BOGOTA = 'Bogotá, D.C.', 'Bogotá, D.C.'
    BOLIVAR = 'Bolívar', 'Bolívar'
    BOYACA = 'Boyacá', 'Boyacá'
    CALDAS = 'Caldas', 'Caldas'
    CAQUETA = 'Caquetá', 'Caquetá'
    CASANARE = 'Casanare', 'Casanare'
    CAUCA = 'Cauca', 'Cauca'
    CESAR = 'Cesar', 'Cesar'
    CHOCO = 'Chocó', 'Chocó'
    CORDOBA = 'Córdoba', 'Córdoba'
    CUNDINAMARCA = 'Cundinamarca', 'Cundinamarca'
    GUAINIA = 'Guainía', 'Guainía'
    GUAVIARE = 'Guaviare', 'Guaviare'
    HUILA = 'Huila', 'Huila'
    LA_GUAJIRA = 'La Guajira', 'La Guajira'
    MAGDALENA = 'Magdalena', 'Magdalena'
    META = 'Meta', 'Meta'
    NARINO = 'Nariño', 'Nariño'
    NORTE_DE_SANTANDER = 'Norte de Santander', 'Norte de Santander'
    PUTUMAYO = 'Putumayo', 'Putumayo'
    QUINDIO = 'Quindío', 'Quindío'
    RISARALDA = 'Risaralda', 'Risaralda'
    SAN_ANDRES = 'San Andrés y Providencia', 'San Andrés y Providencia'
    SANTANDER = 'Santander', 'Santander'
    SUCRE = 'Sucre', 'Sucre'
    TOLIMA = 'Tolima', 'Tolima'
    VALLE_DEL_CAUCA = 'Valle del Cauca', 'Valle del Cauca'
    VAUPES = 'Vaupés', 'Vaupés'
    VICHADA = 'Vichada', 'Vichada'