# Generated by Django 5.0.6 on 2024-05-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena_genius', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento_tipo',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PP', 'PEP'), ('PT', 'Permiso por Protección Temporal')], max_length=50, null=True, verbose_name='Tipo de documento'),
        ),
    ]
